package:
  name: "pyrknn"
  version: 0.0.6

source:
  git_url: https://github.com/ut-padas/pyrknn


requirements:
  host:
    - python {{ python }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools
    - scikit-build
    - numpy
    - cython

  build:
    - openmpi
    - mpi4py
    - python
    - scikit-build
    - mkl
    - mkl-include
    - numpy
      #- cython
      #- mkl
      #- mkl-include
      #- scikit-build
      #- openmpi
      #- mpi4py


  run:
    - numpy
    - scipy
    - psutil
    - numba
    - mpich
    - mpi4py
    - cython
